### ISSUE TITLE
User Settings

### ISSUE THREAD

**Issue by dsabsay** [cpe305/fall2016-project-dsabsay#3]
The user settings need to be stored to the disk.

User settings will be kept in the UserConfiguration object.

What to implement (2 methods in UserConfiguration):
- readUserConfig(): A method to read settings from a file, and change the fields in UserConfiguration (Right now the only field will be rhythmsPath. Don't worry about the other fields.)
- saveUserConfig(): A method to write the current settings in UserConfiguration to a file
## The file that is stored on the disk will look like this:

path/to/rhythms
## ...

Right now there will only be one thing in the file. Other stuff will be added later. Just get the methods set up. The file is located in src/main/resources/userConfiguration.

You can look at src/main/java/com/dsabsay/repo/DefaultPerformanceRecordRepo.java to see how IO was implemented there.

**Comment by RAWeber** [comment]
Crated a pull request for the added features
